import {
  KpiActualSavingsWidget,
  KpiBalanceWidget,
  KpiComplianceWidget,
  KpiContributionsPendingWidget,
  KpiContributionsReceivedWidget,
  KpiHeroWidget,
  KpiMinSavingsWidget,
  KpiOverdueWidget,
  KpiProjectionWidget,
  KpiSavingsRateWidget,
  KpiTotalExpenseWidget,
  KpiTotalIncomeWidget,
  KpiUnallocatedWidget,
} from './kpi-widgets';
import {
  ChartCategoryDoughnutWidget,
  ChartContributionsByMemberWidget,
  ChartFixedVsVariableWidget,
  ChartIncomeVsExpenseWidget,
} from './chart-widgets';
import { UpcomingWidget } from './upcoming-widget';
import type { LayoutItem, WidgetDef } from './widget-types';

/**
 * Master catalogue of widgets available in the dashboard.
 * Keys are stable: do NOT rename or you'll break stored layouts.
 */
export const WIDGETS: Record<string, WidgetDef> = {
  // ---- KPI cards (default 3 wide × 2 tall) -------------------------------
  'kpi-hero': {
    id: 'kpi-hero',
    category: 'kpi',
    labelKey: 'widgets.kpi_hero.label',
    descriptionKey: 'widgets.kpi_hero.description',
    defaultW: 12,
    defaultH: 2,
    minW: 6,
    minH: 2,
    component: KpiHeroWidget,
  },
  'kpi-total-income': {
    id: 'kpi-total-income',
    category: 'kpi',
    labelKey: 'widgets.kpi_total_income.label',
    descriptionKey: 'widgets.kpi_total_income.description',
    defaultW: 3,
    defaultH: 2,
    minW: 2,
    minH: 2,
    component: KpiTotalIncomeWidget,
  },
  'kpi-total-expense': {
    id: 'kpi-total-expense',
    category: 'kpi',
    labelKey: 'widgets.kpi_total_expense.label',
    descriptionKey: 'widgets.kpi_total_expense.description',
    defaultW: 3,
    defaultH: 2,
    minW: 2,
    minH: 2,
    component: KpiTotalExpenseWidget,
  },
  'kpi-balance': {
    id: 'kpi-balance',
    category: 'kpi',
    labelKey: 'widgets.kpi_balance.label',
    descriptionKey: 'widgets.kpi_balance.description',
    defaultW: 3,
    defaultH: 2,
    minW: 2,
    minH: 2,
    component: KpiBalanceWidget,
  },
  'kpi-savings-rate': {
    id: 'kpi-savings-rate',
    category: 'kpi',
    labelKey: 'widgets.kpi_savings_rate.label',
    descriptionKey: 'widgets.kpi_savings_rate.description',
    defaultW: 3,
    defaultH: 2,
    minW: 2,
    minH: 2,
    component: KpiSavingsRateWidget,
  },
  'kpi-overdue': {
    id: 'kpi-overdue',
    category: 'kpi',
    labelKey: 'widgets.kpi_overdue.label',
    descriptionKey: 'widgets.kpi_overdue.description',
    defaultW: 3,
    defaultH: 2,
    minW: 2,
    minH: 2,
    component: KpiOverdueWidget,
  },
  'kpi-min-savings': {
    id: 'kpi-min-savings',
    category: 'kpi',
    labelKey: 'widgets.kpi_min_savings.label',
    descriptionKey: 'widgets.kpi_min_savings.description',
    defaultW: 3,
    defaultH: 2,
    minW: 2,
    minH: 2,
    component: KpiMinSavingsWidget,
  },
  'kpi-actual-savings': {
    id: 'kpi-actual-savings',
    category: 'kpi',
    labelKey: 'widgets.kpi_actual_savings.label',
    descriptionKey: 'widgets.kpi_actual_savings.description',
    defaultW: 3,
    defaultH: 2,
    minW: 2,
    minH: 2,
    component: KpiActualSavingsWidget,
  },
  'kpi-contributions-received': {
    id: 'kpi-contributions-received',
    category: 'kpi',
    labelKey: 'widgets.kpi_contributions_received.label',
    descriptionKey: 'widgets.kpi_contributions_received.description',
    defaultW: 3,
    defaultH: 2,
    minW: 2,
    minH: 2,
    component: KpiContributionsReceivedWidget,
  },
  'kpi-contributions-pending': {
    id: 'kpi-contributions-pending',
    category: 'kpi',
    labelKey: 'widgets.kpi_contributions_pending.label',
    descriptionKey: 'widgets.kpi_contributions_pending.description',
    defaultW: 3,
    defaultH: 2,
    minW: 2,
    minH: 2,
    component: KpiContributionsPendingWidget,
  },
  'kpi-compliance': {
    id: 'kpi-compliance',
    category: 'kpi',
    labelKey: 'widgets.kpi_compliance.label',
    descriptionKey: 'widgets.kpi_compliance.description',
    defaultW: 3,
    defaultH: 2,
    minW: 2,
    minH: 2,
    component: KpiComplianceWidget,
  },
  'kpi-unallocated': {
    id: 'kpi-unallocated',
    category: 'envelope',
    labelKey: 'widgets.kpi_unallocated.label',
    descriptionKey: 'widgets.kpi_unallocated.description',
    defaultW: 3,
    defaultH: 2,
    minW: 2,
    minH: 2,
    component: KpiUnallocatedWidget,
  },
  'kpi-projection': {
    id: 'kpi-projection',
    category: 'projection',
    labelKey: 'widgets.kpi_projection.label',
    descriptionKey: 'widgets.kpi_projection.description',
    defaultW: 6,
    defaultH: 2,
    minW: 4,
    minH: 2,
    component: KpiProjectionWidget,
  },

  // ---- Charts (default 6 wide × 4 tall) ---------------------------------
  'chart-income-vs-expense': {
    id: 'chart-income-vs-expense',
    category: 'chart',
    labelKey: 'widgets.chart_income_vs_expense.label',
    descriptionKey: 'widgets.chart_income_vs_expense.description',
    defaultW: 8,
    defaultH: 4,
    minW: 4,
    minH: 3,
    component: ChartIncomeVsExpenseWidget,
  },
  'chart-category-doughnut': {
    id: 'chart-category-doughnut',
    category: 'chart',
    labelKey: 'widgets.chart_category_doughnut.label',
    descriptionKey: 'widgets.chart_category_doughnut.description',
    defaultW: 4,
    defaultH: 4,
    minW: 3,
    minH: 3,
    component: ChartCategoryDoughnutWidget,
  },
  'chart-contributions-by-member': {
    id: 'chart-contributions-by-member',
    category: 'chart',
    labelKey: 'widgets.chart_contributions_by_member.label',
    descriptionKey: 'widgets.chart_contributions_by_member.description',
    defaultW: 6,
    defaultH: 4,
    minW: 4,
    minH: 3,
    component: ChartContributionsByMemberWidget,
  },
  'chart-fixed-vs-variable': {
    id: 'chart-fixed-vs-variable',
    category: 'chart',
    labelKey: 'widgets.chart_fixed_vs_variable.label',
    descriptionKey: 'widgets.chart_fixed_vs_variable.description',
    defaultW: 6,
    defaultH: 4,
    minW: 3,
    minH: 3,
    component: ChartFixedVsVariableWidget,
  },

  // ---- Lists ------------------------------------------------------------
  'upcoming-timeline': {
    id: 'upcoming-timeline',
    category: 'list',
    labelKey: 'widgets.upcoming_timeline.label',
    descriptionKey: 'widgets.upcoming_timeline.description',
    defaultW: 12,
    defaultH: 6,
    minW: 4,
    minH: 4,
    component: UpcomingWidget,
    multiple: true,
  },
};

/**
 * Default dashboard layout (12-column grid).
 *
 *   1. Hero (full width)
 *   2. Five primary KPIs in one row (equal width)
 *   3. Charts left + upcoming sidebar right
 *   4. Four secondary KPIs in one row
 *   5. Analytical charts + projection
 */
export const DEFAULT_LAYOUT: LayoutItem[] = [
  { instanceId: 'hero', widgetId: 'kpi-hero', x: 0, y: 0, w: 12, h: 2 },

  { instanceId: 'inc', widgetId: 'kpi-total-income', x: 0, y: 2, w: 2, h: 2 },
  { instanceId: 'exp', widgetId: 'kpi-total-expense', x: 2, y: 2, w: 2, h: 2 },
  { instanceId: 'bal', widgetId: 'kpi-balance', x: 4, y: 2, w: 2, h: 2 },
  { instanceId: 'savings', widgetId: 'kpi-savings-rate', x: 6, y: 2, w: 2, h: 2 },
  { instanceId: 'ovd', widgetId: 'kpi-overdue', x: 8, y: 2, w: 2, h: 2 },

  {
    instanceId: 'ive',
    widgetId: 'chart-income-vs-expense',
    x: 0,
    y: 4,
    w: 8,
    h: 4,
  },
  {
    instanceId: 'upcoming',
    widgetId: 'upcoming-timeline',
    x: 8,
    y: 4,
    w: 4,
    h: 8,
  },
  {
    instanceId: 'cdoh',
    widgetId: 'chart-category-doughnut',
    x: 0,
    y: 8,
    w: 4,
    h: 4,
  },
  {
    instanceId: 'fvv',
    widgetId: 'chart-fixed-vs-variable',
    x: 4,
    y: 8,
    w: 4,
    h: 4,
  },

  {
    instanceId: 'cr',
    widgetId: 'kpi-contributions-received',
    x: 0,
    y: 12,
    w: 3,
    h: 2,
  },
  {
    instanceId: 'cp',
    widgetId: 'kpi-contributions-pending',
    x: 3,
    y: 12,
    w: 3,
    h: 2,
  },
  { instanceId: 'minsav', widgetId: 'kpi-min-savings', x: 6, y: 12, w: 3, h: 2 },
  {
    instanceId: 'actsav',
    widgetId: 'kpi-actual-savings',
    x: 9,
    y: 12,
    w: 3,
    h: 2,
  },

  {
    instanceId: 'cbym',
    widgetId: 'chart-contributions-by-member',
    x: 0,
    y: 14,
    w: 6,
    h: 4,
  },
  {
    instanceId: 'proj',
    widgetId: 'kpi-projection',
    x: 6,
    y: 14,
    w: 6,
    h: 2,
  },
];
